trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    sudo apt-get update
    sudo apt-get install curl
    sudo apt-get install wget
    sudo apt-get install -y ca-certificates
    npm install -g npm
  displayName: 'Installing CURL and WGET'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Extentias-SonarQube'
    scannerMode: 'CLI'
    configMode: 'file'
- task: SonarQubeAnalyze@4