trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    sudo apt-get update
    sudo apt-get install curl
    sudo apt-get install wget
  displayName: 'Installing CURL and WGET'

- script: |
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
    pwd
    ls -l
  displayName: 'Downloading sonar scanner'  

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(/home/vsts/work/1/s/sonar-scanner-cli-4.4.0.2170-linux.zip)'
    destinationFolder: '$(agent.builddirectory)'
    cleanDestinationFolder: true
  displayName: 'Extracting the zip file'  

- script: |
    pwd
    ls -l
