trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    sudo apt-get install curl
    sudo apt-get install wget
  displayName: 'Installing CURL and WGET'

- script:
    echo '#########################Contents of /etc/hosts file are listed below##########################'
    cat /etc/hosts