trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@latest
    npm i
    sudo apt-get update
    sudo apt-get install curl
    sudo apt-get install wget
    pwd && ls -l
  displayName: 'Installing Dependencies'

- script: |
    ng build
    cd dist && ls -l
  displayName: 'Building the application and deploying'

- script: |
    npm run e2e
  displayName: 'Running unit tests'
  

- script: |
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
    pwd
    ls -l
    unzip *.zip 
  displayName: 'Downloading sonar scanner' 

- script: |
    /home/vsts/work/1/s/sonar-scanner-4.4.0.2170-linux/bin/sonar-scanner
  displayName: 'Executing Sonar scanner'  