trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    pwd
    ls -l

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Extentias-SonarQube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Azure-Integration-EMS'
    cliProjectName: 'Azure-Integration-EMS'
    cliSources: '.'

- task: SonarQubeAnalyze@4
