trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    sudo apt-get install curl
    sudo apt-get install wget
    npm install -g npm
  displayName: 'Installing CURL and WGET'

- task: SonarQubePrepare@4
  inputs:
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Azure-Project-Test'
    cliProjectName: 'Azure-Project-Test'
    cliSources: '.'
    extraProperties: 'sonar.host.url=https://sonar.extentia.com/'